language: cpp
compiler: gcc
dist: trusty
sudo: required
branches:
  only:
    - develop
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
install:
  - sudo apt-get upgrade --yes
script:
  - mkdir build && cd build && cmake .. && make
  - ./xzbuf-test