language: cpp
compiler: gcc
dist: trusty
sudo: required
branches:
  only:
    - develop
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
      - gcc-5
      - g++-5
install:
   - curl -L https://github.com/facebook/zstd/archive/v1.2.0.tar.gz > zstd-v1.2.0.tar.gz
   - tar -xzf zstd-v1.2.0.tar.gz
   - cd zstd-1.2.0/ && cmake -DCMAKE_BUILD_TYPE=Release -DZSTD_BUILD_STATIC=1 build/cmake && make && sudo make install && cd ..
#  - sudo apt-get install --yes --only-upgrade cmake-data
#  - sudo apt-get install --yes --only-upgrade cmake
script:
  - cmake --version
  - mkdir build && cd build
  - cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-5 -DCMAKE_CXX_COMPILER=/usr/bin/g++-5 .. || echo ""
  - make
  - make CTEST_OUTPUT_ON_FAILURE=1 test