language: cpp
compiler: gcc
dist: trusty
sudo: required
branches:
  only:
    - develop
#addons:
#  apt:
#    sources:
#      - george-edison55-precise-backports
#    packages:
#      - cmake
#      - cmake-data
#install:
#  - sudo apt-get install --yes --only-upgrade cmake-data
#  - sudo apt-get install --yes --only-upgrade cmake
script:
  - mkdir build && cd build
  - cmake ..
  - make
  - export CTEST_OUTPUT_ON_FAILURE=1
  - make test