language: cpp
compiler: gcc
dist: trusty
sudo: required
branches:
  only:
    - develop
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
#install:
#  - sudo apt-get install --yes --only-upgrade cmake-data
#  - sudo apt-get install --yes --only-upgrade cmake
script:
  - cmake --version
  - mkdir build && cd build
  - cmake .. || echo ""
  - make
  - make CTEST_OUTPUT_ON_FAILURE=1 test