language: cpp
compiler: gcc
branches:
  only:
    - develop
install:
  - sudo add-apt-repository ppa:george-edison55/precise-backports --yes
  - sudo apt-get update
  - sudo apt-get install cmake
script:
  - mkdir build && cd build && cmake .. && make
  - ./xzbuf-test