language: cpp
compiler: gcc
dist: trusty
sudo: required
branches:
  only:
    - develop
addons:
  apt:
    sources:
      - ppa:george-edison55/cmake-3.x
    packages:
      - cmake
      - cmake-data
script:
  - mkdir build && cd build && cmake .. && make
  - ./xzbuf-test